# SBOM scan configuration for release CI. The generation script supplies
# explicit CycloneDX and SPDX output paths and records their SHA-256 hashes.
check-for-app-update: false
format:
  pretty: true
file:
  metadata:
    selection: "none"
    digests:
      - "sha256"
exclude:
  - "./.build/**"
  - "./.git/**"
  - "./.swiftpm/**"
  - "./artifacts/**"
